FROM node:13.12.0-alpine

COPY ./src/frontend/package.json ./
COPY ./src/frontend/package-lock.json ./
RUN npm install --silent
RUN npm install react-scripts@3.4.1 -g --silent

COPY ./src/frontend ./
WORKDIR ./

EXPOSE 3000

ENV PATH /node_modules/.bin:$PATH

CMD ["npm", "start"]
