"""Add user_type to the users table

Revision ID: 0ea564192726
Revises: 280a5af04483
Create Date: 2020-12-16 21:23:54.816894

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "0ea564192726"
down_revision = "280a5af04483"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("user_type", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "user_type")
    # ### end Alembic commands ###
