"""Add internships table

Revision ID: 3afe176dd844
Revises: 88bead6966d0
Create Date: 2020-12-19 12:16:44.064313

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "3afe176dd844"
down_revision = "88bead6966d0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "internships",
        sa.Column("internship_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column(
            "description", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("company_mail", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_mail"],
            ["users.mail"],
        ),
        sa.PrimaryKeyConstraint("internship_id"),
    )
    op.create_table(
        "internship_views",
        sa.Column("internship_id", sa.Integer(), nullable=False),
        sa.Column("user_mail", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["internship_id"],
            ["internships.internship_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_mail"],
            ["users.mail"],
        ),
        sa.PrimaryKeyConstraint("internship_id", "user_mail"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("internship_views")
    op.drop_table("internships")
    # ### end Alembic commands ###
